### ISSUE TITLE
Image Preprocessing

### ISSUE THREAD

**Issue by Sakina-1** [MATS64662-2020-Group-1/FEM#24]
The images provided need to be smoother/clearer so that the simulation results are better.

**Comment by JoshUoM** [comment]
Hi Sakina, which image is this?

**Comment by Sakina-1** [comment]
<img width="113" alt="test" src="https://user-images.githubusercontent.com/56676978/83788334-f092b480-a68c-11ea-9a87-2f90ddf01156.png">

This image could be clearer? Just any part of the Ti64 images that are clear with multiple grains would be nice.

I'm looking for an image as clear as this:

<img width="73" alt="grain" src="https://user-images.githubusercontent.com/56676978/83788467-246dda00-a68d-11ea-9b12-7addc0b05d4f.png">

**Comment by JoshUoM** [comment]
See new pull request in Image-Processing
