### ISSUE TITLE
Fixed Displacements on the LHS of Image

### ISSUE THREAD

**Issue by Sakina-1** [MATS64662-2020-Group-1/FEM#33]
Just to let you know that in the new test cases the displacements have been fixed on the LHS, not the RHS. " i.e. LHS: x, y is fixed at 0"

**Comment by Gbowker** [comment]
So for test case 5 should I hold the LHS and displace the RHS? Did you also do the same for temperature? Initialising LHS with room T and RHS with higher T?

**Comment by fsl506** [comment]
Please keep the boundary conditions constant. So fix the LHS at (0,0). The
highest temperature is on the RHS, at 1000 and 0 on the LHS in the test
cases.

**Comment by fsl506** [comment]
Thanks for sorting them out again, Sakina!
